spring.application.name=quizapp
spring.datasource.url=jdbc:postgresql://localhost:5432/quizdb
spring.datasource.username=quizuser
spring.datasource.password=quizpass

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect